site_name: Project Ordinance Wiki
site_description: Official knowledge base for Project Ordinance
site_author: Project Ordinance
site_url: https://wiki.project-ordinance.com
copyright: "© Project Ordinance"

theme:
  name: material
  logo: assets/logo_black.ico
  favicon: assets/logo_black.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - search.highlight
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/github

extra_css:
  - styles/extra.css
extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - macros
  - mermaid2

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview:
    - Home: index.md
    - Goals & Vision: about/vision.md
    - FAQ: about/faq.md
    - Changelog: changelog.md
  - Team:
    - Current Team: team/index.md
  - Projects:
    - Overview: projects/index.md
    - The Main Server: projects/main-server.md
    - Escape: projects/escape.md
    - Deathmatch: projects/deathmatch.md
  - Characters:
    - Registry: characters/index.md
  - Systems:
    - Systems Overview: systems/index.md
    - Anti mass spectrometer: systems/ams.md
  - Maps:
    - Map Guide: maps/index.md
  - Lore:
    - Lore Overview: lore/index.md
    - Important Events: lore/events.md
    - Notable Figures: lore/figures.md
